# You can override the included template(s) by including variable overrides
# SAST customization: https://docs.gitlab.com/ee/user/application_security/sast/#customizing-the-sast-settings
# Secret Detection customization: https://docs.gitlab.com/ee/user/application_security/secret_detection/#customizing-settings
# Dependency Scanning customization: https://docs.gitlab.com/ee/user/application_security/dependency_scanning/#customizing-the-dependency-scanning-settings
# Container Scanning customization: https://docs.gitlab.com/ee/user/application_security/container_scanning/#customizing-the-container-scanning-settings
# Note that environment variables can be set in several places
# See https://docs.gitlab.com/ee/ci/variables/#cicd-variable-precedence
default:
    tags:
        - shared-fi

variables:
    GIT_CLEAN_FLAGS: "-f -e node_modules/ -e .nx/"

stages:
    - prepare
    - lint
    - test
    - build
    - sast

cache:
    key: ${CI_COMMIT_REF_SLUG}
    paths:
        - node_modules/
        - .nx/cache/

prepare:
    stage: prepare
    image: node:latest
    script:
        - npm install nx
        - npm install

lint:
    stage: lint
    image: node:latest
    script:
        - npm ci
        - nx run-many --target=lint --verbose=true--all=true
    needs:
        - ["prepare"]

test:
    stage: test
    image: node:latest
    script:
        - npm ci
        - nx run-many --target=test --verbose=true --all=true --passWithNoTests
    needs:
        - ["prepare"]

build:
    stage: build
    image: node:latest
    script:
        - npm ci
        - nx run-many --target=build --verbose=true --all=true
    needs:
        - ["prepare"]

sast:
    stage: sast
    needs:
        - ["build"]

include:
    - template: Security/SAST.gitlab-ci.yml
