openapi: 3.0.0
info:
    title: PCAssemblies
    description: Backend Api for the PC Assemblies application
    version: 0.0.1
servers:
    - url: http://localhost:8080

components:
    schemas:
        UserRegistrationDTO:
            type: object
            properties:
                username:
                    type: string
                email:
                    type: string
                    format: email
                password:
                    type: string
                userType:
                    $ref: "#/components/schemas/UserType"
            required:
                - username
                - email
                - password
                - userType
        UserLoginDTO:
            type: object
            properties:
                email:
                    type: string
                    format: email
                password:
                    type: string
            required:
                - email
                - password
        UserUpdateDTO:
            type: object
            properties:
                id:
                    type: integer
                    format: int64
                username:
                    type: string
                email:
                    type: string
                    format: email
                encryptedPassword:
                    type: string
                userType:
                    $ref: "#/components/schemas/UserType"
            required:
                - id
        ConfigurationCreateDTO:
            type: object
            properties:
                userId:
                    type: integer
                    format: int64
                motherboardId:
                    $ref: "#/components/schemas/MotherboardDTO"
                processorId:
                    $ref: "#/components/schemas/ProcessorDTO"
                gpuId:
                    $ref: "#/components/schemas/GPUDTO"
                ramIds:
                    type: array
                    items:
                        $ref: "#/components/schemas/RAMDTO"
                storageIds:
                    type: array
                    items:
                        $ref: "#/components/schemas/StorageDTO"
                powerSupplyId:
                    $ref: "#/components/schemas/PowerSupplyDTO"
                pcCaseId:
                    $ref: "#/components/schemas/PCCaseDTO"
            required:
                - userId
                - motherboardId
                - processorId
                - gpuId
                - ramIds
                - storageIds
                - powerSupplyId
                - pcCaseId
        ConfigurationUpdateDTO:
            type: object
            properties:
                id:
                    type: integer
                    format: int64
                userId:
                    type: integer
                    format: int64
                motherboardId:
                    $ref: "#/components/schemas/MotherboardDTO"
                processorId:
                    $ref: "#/components/schemas/ProcessorDTO"
                gpuId:
                    $ref: "#/components/schemas/GPUDTO"
                ramIds:
                    type: array
                    items:
                        $ref: "#/components/schemas/RAMDTO"
                storageIds:
                    type: array
                    items:
                        $ref: "#/components/schemas/StorageDTO"
                powerSupplyId:
                    $ref: "#/components/schemas/PowerSupplyDTO"
                pcCaseId:
                    $ref: "#/components/schemas/PCCaseDTO"
            required:
                - id
                - userId
        UserType:
            type: string
            enum:
                - ADMIN
                - USER
        MotherboardDTO:
            type: object
            properties:
                socket:
                    type: string
                formFactor:
                    type: string
                ramSlots:
                    type: integer
                ramType:
                    type: string
                gpuInterface:
                    type: string
                storageBusType:
                    type: string
        ProcessorDTO:
            type: object
            properties:
                architecture:
                    type: string
                cores:
                    type: integer
                threads:
                    type: integer
                bits:
                    type: integer
                socket:
                    type: string
        GPUDTO:
            type: object
            properties:
                memory:
                    type: integer
                powerConnector:
                    type: string
                interface:
                    type: string
                power:
                    type: integer
        RAMDTO:
            type: object
            properties:
                memoryType:
                    type: string
                capacity:
                    type: integer
                computerType:
                    type: string
        StorageDTO:
            type: object
            properties:
                storageType:
                    type: string
                capacity:
                    type: integer
                    format: int64
                busType:
                    type: string
        PowerSupplyDTO:
            type: object
            properties:
                powerOutput:
                    type: integer
                efficiency:
                    type: string
                formFactor:
                    type: string
        PCCaseDTO:
            type: object
            properties:
                formFactor:
                    type: string

paths:
    /users/register:
        post:
            summary: Register a new user
            requestBody:
                required: true
                content:
                    application/json:
                        schema:
                            $ref: "#/components/schemas/UserRegistrationDTO"
            responses:
                "200":
                    description: User registration successful
    /users/login:
        post:
            summary: Log in as a user
            requestBody:
                required: true
                content:
                    application/json:
                        schema:
                            $ref: "#/components/schemas/UserLoginDTO"
            responses:
                "200":
                    description: User login successful
    /users/{userId}:
        put:
            summary: Update user details
            parameters:
                - in: path
                  name: userId
                  required: true
                  description: ID of the user to update
                  schema:
                      type: integer
                      format: int64
            requestBody:
                required: true
                content:
                    application/json:
                        schema:
                            $ref: "#/components/schemas/UserUpdateDTO"
            responses:
                "200":
                    description: User details updated successfully
    /configurations:
        post:
            summary: Create a new PC configuration
            requestBody:
                required: true
                content:
                    application/json:
                        schema:
                            $ref: "#/components/schemas/ConfigurationCreateDTO"
            responses:
                "200":
                    description: PC configuration created successfully
        put:
            summary: Update an existing PC configuration
            parameters:
                - in: path
                  name: configurationId
                  required: true
                  description: ID of the configuration to update
                  schema:
                      type: integer
                      format: int64
            requestBody:
                required: true
                content:
                    application/json:
                        schema:
                            $ref: "#/components/schemas/ConfigurationUpdateDTO"
            responses:
                "200":
                    description: PC configuration updated successfully
