openapi: 3.1.0
info:
    title: PCAssemblies
    description: Backend Api for the PC Assemblies application
    version: 0.0.1
servers:
    - url: "{scheme}//{server}:{port}"
      description: the server
      variables:
          scheme:
              default: "http:"
              enum:
                  - "http:"
                  - "https:"
          server:
              default: localhost
          port:
              default: "8080"

security:
    - sessionCookie: []

components:
    schemas:
        Security:
            SessionCookie:
                type: apiKey
                in: cookie
                name: session

        # User:
        UserDTO:
            $ref: "./schemas/user/UserDTO.yaml"
        UserUpdateDTO:
            $ref: "./schemas/user/UserUpdateDTO.yaml"
        UserLoginDTO:
            $ref: "./schemas/user/UserLoginDTO.yaml"
        UserRegistrationDTO:
            $ref: "./schemas/user/UserRegistrationDTO.yaml"
        UserType:
            $ref: "./schemas/user/UserType.yaml"

        # Components:
        GPUDTO:
            $ref: "./schemas/components/GPUDTO.yaml"
        MotherboardDTO:
            $ref: "./schemas/components/MotherboardDTO.yaml"
        PCCaseDTO:
            $ref: "./schemas/components/PCCaseDTO.yaml"
        PowerSupplyDTO:
            $ref: "./schemas/components/PowerSupplyDTO.yaml"
        ProcessorDTO:
            $ref: "./schemas/components/ProcessorDTO.yaml"
        RAMDTO:
            $ref: "./schemas/components/RAMDTO.yaml"
        StorageDTO:
            $ref: "./schemas/components/StorageDTO.yaml"

        # Configuration:
        ConfigurationCreateDTO:
            $ref: "./schemas/configuration/ConfigurationCreateDTO.yaml"
        ConfigurationDTO:
            $ref: "./schemas/configuration/ConfigurationDTO.yaml"
        ConfigurationUpdateDTO:
            $ref: "./schemas/configuration/ConfigurationUpdateDTO.yaml"

        # PartialConfiguration:
        PartialConfigurationCreateDTO:
            $ref: "./schemas/partial-configuration/PartialConfigurationCreateDTO.yaml"
        PartialConfigurationDTO:
            $ref: "./schemas/partial-configuration/PartialConfigurationDTO.yaml"
        PartialConfigurationUpdateDTO:
            $ref: "./schemas/partial-configuration/PartialConfigurationCreateDTO.yaml"

        # Responses:
        BadRequestError:
            $ref: "./schemas/responses/BadRequestError.yaml"
        ConfigurationList:
            $ref: "./schemas/responses/ConfigurationList.yaml"
        InternalServerError:
            $ref: "./schemas/responses/InternalServerError.yaml"
        LoginSuccess:
            $ref: "./schemas/responses/LoginSuccess.yaml"
        NotFoundError:
            $ref: "./schemas/responses/NotFoundError.yaml"
        Success:
            $ref: "./schemas/responses/Success.yaml"

    responses:
        BadRequestErrorResponse:
            $ref: "./responses/BadRequestErrorResponse.yaml"
        InternalServerError:
            $ref: "./responses/InternalServerErrorResponse.yaml"
        SuccessResponse:
            $ref: "./responses/SuccessResponse.yaml"
        ConfigurationListResponse:
            $ref: "./responses/ConfigurationListResponse.yaml"
        NotFoundErrorResponse:
            $ref: "./responses/NotFoundErrorResponse.yaml"

paths:
    /users/register:
        $ref: "./routes/auth.yaml#/register"
    /users/login:
        $ref: "./routes/auth.yaml#/login"
    /users/{userId}:
        $ref: "./routes/users.yaml#/usersUserId"
    /configurations:
        $ref: "./routes/configurations.yaml#/configurations"
    /configurations/{userId}:
        $ref: "./routes/configurations.yaml#/configurationsUserId"
    /configurations/partial:
        $ref: "./routes/configurations.yaml#/partialConfigurations"
    /configurations/partial/{userId}:
        $ref: "./routes/configurations.yaml#/partialConfigurationsUserId"
    /components/gpus:
        $ref: "./routes/components/gpus.yaml#/gpus"
    /components/gpus/{gpuId}:
        $ref: "./routes/components/gpus.yaml#/gpusGpuId"
    /components/motherboards:
        $ref: "./routes/components/motherboards.yaml#/motherboards"
    /components/motherboards/{motherboardId}:
        $ref: "./routes/components/motherboards.yaml#/motherboardsMotherboardId"
    /components/pccases:
        $ref: "./routes/components/pccases.yaml#/pccases"
    /components/pccases/{pcCaseId}:
        $ref: "./routes/components/pccases.yaml#/pccasesPcCaseId"
    /components/powersupplies:
        $ref: "./routes/components/powersupplies.yaml#/powersupplies"
    /components/powersupplies/{powersupplyid}:
        $ref: "./routes/components/powersupplies.yaml#/powersuppliesPowerSupplyId"
    /components/processors:
        $ref: "./routes/components/processors.yaml#/processors"
    /components/processors/{processorId}:
        $ref: "./routes/components/processors.yaml#/processorsProcessorId"
    /components/rams:
        $ref: "./routes/components/rams.yaml#/rams"
    /components/rams/{ramId}:
        $ref: "./routes/components/rams.yaml#/ramsRamId"
    /components/storages:
        $ref: "./routes/components/storages.yaml#/storages"
    /components/storages/{storageId}:
        $ref: "./routes/components/storages.yaml#/storagesStorageId"
